version: '3.4'

services:
  database_postgresql:
    image: postgres:latest
    ports:
      - 9432:5432
    environment:
      - POSTGRES_DB=z-games
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpass123

  database_mongodb:
    image: mongo:latest
    ports:
      - 29017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=dbpass123

  api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - 4000:4000
    depends_on:
      - database_postgresql
      - database_mongodb
